[package]
authors = ['Terry Brashaw <terrybrashaw@gmail.com>']
build = 'build.rs'
edition = '2018'
name = 'grifter'
version = '0.1.0'

[dependencies]
flate2 = '1.0.18'
json = '0.12.4'
rocket_contrib = '0.4.5'
rocket_cors = '0.5.2'
serde_json = '1.0.59'
toml = '0.5.7'
unicode-normalization = '0.1.13'

[dependencies.ureq]
features = ['json']
version = '1.5.1'

[dependencies.serde]
features = ['derive']
version = '1.0.116'

[dependencies.rocket]
default-features = false
version = '0.4.5'
